---
# tasks file for 3zabbix
- name: install_zabbix_from_repo_online
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present

- name: install_package_needed
  dnf:
    name:
      - python3-PyMySQL
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-agent
    state: present

- name: import_initial_db
  mysql_db:
    name: "{{ dbname }}"
    state: import
    target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
    login_user: "{{ dbuser }}"
    login_host: "{{ dbhost_server }}"
    login_password: "{{ dbpass }}"
  run_once: true
  ignore_errors: yes


- name: edit_conf_zabbix_server
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: '# DBPassword=', line: 'DBPassword={{ dbpass }}'}
    - { regexp: '# DBHost=', line: 'DBHost={{ dbhost_server }}'}

- name: edit_php-fpm.d_conf_zabbix_server
  lineinfile:
    path: //etc/php-fpm.d/zabbix.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: '; php_value[date.timezone]', line: 'php_value[date.timezone] = Asia/Jakarta'}

- name: restart_and_enable_zabbix_server,zabbix_agent,httpd,php-fpm
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm